[project]
name = "support-two"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "support-one"
]

[tool.uv.sources]
support-one = { workspace = true }
